[
    {
        "snapshot_id": "a649e085-10c8-430a-a882-91b921b9f94d",
        "name": "topology",
        "created_at": 1784693584,
        "description": "Snapshot 'topology' taken on 2026-07-22 at 04:13:04",
        "filename": "topology.gns3snapshot",
        "project_id": "20a8143a-e44e-4c5e-a1a4-77d215996f09"
    }
]