[
    {
        "snapshot_id": "f7777c21-7126-4bc4-8cc2-9d975d0e8954",
        "name": "Layer 2 and Layer 3 Foundation",
        "created_at": 1784779920,
        "description": "Snapshot 'Layer 2 and Layer 3 Foundation' taken on 2026-07-23 at 04:12:00",
        "filename": "Layer 2 and Layer 3 Foundation.gns3snapshot",
        "project_id": "20a8143a-e44e-4c5e-a1a4-77d215996f09"
    },
    {
        "snapshot_id": "6cec2c35-77ba-44e4-b333-af55e089e2c3",
        "name": "Before ACL",
        "created_at": 1784829709,
        "description": "Snapshot 'Before ACL' taken on 2026-07-23 at 18:01:49",
        "filename": "Before ACL.gns3snapshot",
        "project_id": "20a8143a-e44e-4c5e-a1a4-77d215996f09"
    },
    {
        "snapshot_id": "69e1213f-40bc-40d8-a2f1-46f72d2773a7",
        "name": "Pre Redesign",
        "created_at": 1785131489,
        "description": "Snapshot 'Pre Redesign' taken on 2026-07-27 at 05:51:29",
        "filename": "Pre Redesign.gns3snapshot",
        "project_id": "20a8143a-e44e-4c5e-a1a4-77d215996f09"
    },
    {
        "snapshot_id": "9f15248f-df2a-47c0-b855-92f17834e3e5",
        "name": "Put ACL",
        "created_at": 1785230078,
        "description": "Snapshot 'Put ACL' taken on 2026-07-28 at 09:14:38",
        "filename": "Put ACL.gns3snapshot",
        "project_id": "20a8143a-e44e-4c5e-a1a4-77d215996f09"
    },
    {
        "snapshot_id": "eb96016d-17eb-422f-a692-057437da5a94",
        "name": "Routing complete",
        "created_at": 1785236166,
        "description": "Snapshot 'Routing complete' taken on 2026-07-28 at 10:56:06",
        "filename": "Routing complete.gns3snapshot",
        "project_id": "20a8143a-e44e-4c5e-a1a4-77d215996f09"
    },
    {
        "snapshot_id": "8f0b08bc-feba-4a39-a9d6-b857d085dcd7",
        "name": "Access Switches complete",
        "created_at": 1785236820,
        "description": "Snapshot 'Access Switches complete' taken on 2026-07-28 at 11:07:00",
        "filename": "Access Switches complete.gns3snapshot",
        "project_id": "20a8143a-e44e-4c5e-a1a4-77d215996f09"
    },
    {
        "snapshot_id": "1461f25e-441d-4442-92d9-0eb70a2e176f",
        "name": "Add ssh to all devices",
        "created_at": 1785435357,
        "description": "Snapshot 'Add ssh to all devices' taken on 2026-07-30 at 18:15:57",
        "filename": "Add ssh to all devices.gns3snapshot",
        "project_id": "20a8143a-e44e-4c5e-a1a4-77d215996f09"
    }
]